project:
  name: 'JSON_to_PGSQL'
  dir: 'C:/Users/delst/OneDrive/Desktop/Code/Workspace/JSON_to_PGSQL'

password:
  postgres_password: 'C:/Users/delst/OneDrive/Desktop/Code/Workspace/JSON_to_PGSQL/Sensitive/postgresql_pw.txt'

sys:
  fig_size_m: [20,15] # Monitor
  fig_size_l: [12,12] # Laptop

data:
  raw_data: 'C:/Users/delst/OneDrive/Desktop/Code/Workspace/JSON_to_PGSQL/Data/A_Raw/raw_data.json'
  # raw_data_train: ''
  # raw_data_val: ''
  # raw_data_test: ''

sdo:
  sdo_feather: 'C:/Users/delst/OneDrive/Desktop/Code/Workspace/JSON_to_PGSQL/Data/Serialised_Data_Objects/Feather'
  sdo_parq: 'C:/Users/delst/OneDrive/Desktop/Code/Workspace/JSON_to_PGSQL/Data/Serialised_Data_Objects/Parq'
  sdo_pkl: 'C:/Users/delst/OneDrive/Desktop/Code/Workspace/JSON_to_PGSQL/Data/Serialised_Data_Objects/Pkl'

